[package]
name = "rust-custom-commands"
version = "0.1.0"
authors = ["drklee3 <drklee3@users.noreply.github.com>"]

[dependencies]
serenity = "0.4"
dotenv = "0.10.1"
rusqlite = "0.12.0"
env_logger = "0.4.3"
log = "0.3"